//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeCube.Core.Extensions.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodeCube.Core.Resources.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to one minute ago.
        /// </summary>
        internal static string AMinuteAgo {
            get {
                return ResourceManager.GetString("AMinuteAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in one hour.
        /// </summary>
        internal static string InAnHour {
            get {
                return ResourceManager.GetString("InAnHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in a minute.
        /// </summary>
        internal static string InAnMinute {
            get {
                return ResourceManager.GetString("InAnMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in one week.
        /// </summary>
        internal static string InAWeek {
            get {
                return ResourceManager.GetString("InAWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in {0} days.
        /// </summary>
        internal static string InXDays {
            get {
                return ResourceManager.GetString("InXDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in {0} hours.
        /// </summary>
        internal static string InXHours {
            get {
                return ResourceManager.GetString("InXHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in {0} minutes.
        /// </summary>
        internal static string InXMinutes {
            get {
                return ResourceManager.GetString("InXMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in {0} months.
        /// </summary>
        internal static string InXMonths {
            get {
                return ResourceManager.GetString("InXMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in {0} weeks.
        /// </summary>
        internal static string InXWeeks {
            get {
                return ResourceManager.GetString("InXWeeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to just now.
        /// </summary>
        internal static string JustNow {
            get {
                return ResourceManager.GetString("JustNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make a choice.
        /// </summary>
        internal static string MakeAChoice {
            get {
                return ResourceManager.GetString("MakeAChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to an hour ago.
        /// </summary>
        internal static string OneHourAgo {
            get {
                return ResourceManager.GetString("OneHourAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to one week ago.
        /// </summary>
        internal static string OneWeekAgo {
            get {
                return ResourceManager.GetString("OneWeekAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an option.
        /// </summary>
        internal static string SelectAnItem {
            get {
                return ResourceManager.GetString("SelectAnItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tomorrow.
        /// </summary>
        internal static string Tomorrow {
            get {
                return ResourceManager.GetString("Tomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} days ago.
        /// </summary>
        internal static string xDaysAgo {
            get {
                return ResourceManager.GetString("xDaysAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hours ago.
        /// </summary>
        internal static string xHoursAgo {
            get {
                return ResourceManager.GetString("xHoursAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minuten geleden.
        /// </summary>
        internal static string xMinutesAgo {
            get {
                return ResourceManager.GetString("xMinutesAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} months ago.
        /// </summary>
        internal static string xMonthsAgo {
            get {
                return ResourceManager.GetString("xMonthsAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} weeks ago.
        /// </summary>
        internal static string xWeeksAgo {
            get {
                return ResourceManager.GetString("xWeeksAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} years ago.
        /// </summary>
        internal static string xYearsAgo {
            get {
                return ResourceManager.GetString("xYearsAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yesterday.
        /// </summary>
        internal static string Yesterday {
            get {
                return ResourceManager.GetString("Yesterday", resourceCulture);
            }
        }
    }
}
